### ISSUE TITLE
Making frontend design 

### ISSUE THREAD

**Issue by Serjeel-Ranjan-911** [Serjeel-Ranjan-911/duckduckgoThemeMaker#1]
need a build a decent UI for current application. Currently app contains almost no css. This project is very minimal so we can go with any type of design (designers playground ) look on dribble for inspiration  (can go with any funky look or modern like discord). 

We will have further discussion here on how this thing should go. (don't jump into code directly)
This is going to be decent amount of work so if interested in working then comment here.

**Comment by bhargavkumar7031** [comment]
Hi @Serjeel-Ranjan-911,interested in working but few questions

css or scss?
Can u share the design from dribble so that we can get started. or should i search for them?

**Comment by Serjeel-Ranjan-911** [comment]
@bhargavkumar7031 
> css or scss?

anything is fine. I usually work in scss since I find it more comfortable, for this project anything will be fine. (If you have not worked with scss before then maybe this is the best time to get started with it. Trust me it's a shift you will never regret )



> Can u share the design from dribble so that we can get started. or should I search for them?

I have not decided any style for it. Just want some cool style otherwise could have used tailwind css or something. you select any styles from dribble. I have started discussion. we will further discuss there. 

Thanks for joining in :thumbsup:

**Comment by bhargavkumar7031** [comment]
okay with tailwind css or dribbble design. ill start with scss
