### ISSUE TITLE
Don't work

### ISSUE THREAD

**Issue by Dedsd** [Serjeel-Ranjan-911/duckduckgoThemeMaker#3]
I made a theme and i can't get or view in browser

**Comment by Serjeel-Ranjan-911** [comment]
@Dedsd  can you elaborate what difficulty you faced?
did you follow steps to apply it?
```

- go to duckduckgo.com

- open browser console and paste below code. (Ctrl-Shift-C or Right-Click Inspect)


	["ae=g","7=ffffff","8=444444","9=1a0dab","j=262626","aa=5500a3","x=006621"].forEach(e=>document.cookie=e);

        alert('Appearance settings have successfully been updated!');

        location.reload();
		

- done! Enjoy you colors with privacy

```

**Comment by Dedsd** [comment]
Actually other thing, could you help me what this ["ae=g","7=ffffff","8=444444","9=1a0dab","j=262626","aa=5500a3","x=006621"]
colors is, because in duckduckgo we have the appearance tab. I had made a theme and i would like to create a code for other people use.

**Comment by Serjeel-Ranjan-911** [comment]
The website generate this code once you click on "get this theme" button after choosing your colors. Then you can follow steps

**Comment by Dedsd** [comment]
![Peek 29-08-2021 19-46](https://user-images.githubusercontent.com/71463162/131267701-a1577467-6166-4586-bab8-2a2599947e5f.gif)

**Comment by Serjeel-Ranjan-911** [comment]
Scroll down after clicking 😅 @Dedsd

**Comment by Dedsd** [comment]
Oh hahahaha sorry
