### ISSUE TITLE
Scroll down to bottom on click.

### ISSUE THREAD

**Issue by Serjeel-Ranjan-911** [Serjeel-Ranjan-911/duckduckgoThemeMaker#4]
On clicking "get this theme" (on create Page) button the window should scroll down to show newly added component.

**Comment by Rajat-patel19** [comment]
hey i wanted to work on this , can anyone help me out cause i am a beginner

**Comment by Serjeel-Ranjan-911** [comment]
@Rajat-patel19  yes ask me any doubts you have

**Comment by Rajat-patel19** [comment]
so how should i start

**Comment by Serjeel-Ranjan-911** [comment]
The following steps you should follow 

- start by forking this repository
- then clone your forked repository in your machine
- from here you can start working on this react project (I assume this part you can do)
- once you are done making your changes commit your changes to a new branch
- push your new branch to your forked repo
- finally raise pull request

**Comment by Rajat-patel19** [comment]
i have forked and cloned the repo

**Comment by Serjeel-Ranjan-911** [comment]
great 
![image](https://user-images.githubusercontent.com/74287984/132094505-016025db-fe46-4175-be1f-38f13834ec32.png)
your work is to scroll down the window once button is clicked

**Comment by Rajat-patel19** [comment]
okayy and after scrolling to bottom what else is to be done?

**Comment by Serjeel-Ranjan-911** [comment]
currently nothing

**Comment by Rajat-patel19** [comment]
Hey can you help me suggesting an approach.
i was making a scroll function and passing it in on click function but it is not working.

**Comment by Serjeel-Ranjan-911** [comment]
search how to scroll to a particular element in react. you may find resources from there

**Comment by Serjeel-Ranjan-911** [comment]
@Rajat-patel19 ok scroll is fine. The issue is it doesn't work on first click

**Comment by Rajat-patel19** [comment]
i have corrected it you can check it out
